data:
  image: busybox
  container_name: data
  volumes:
    - /opt/elasticsearch/data
  command: /bin/true
elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  build: dockerfiles/elasticsearch
  volumes_from:
    - data
logs:
  extends:
    file: docker-compose-common.yml
    service: logstash
  build: dockerfiles/logstash
  links:
    - elasticsearch:elasticsearch
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  build: dockerfiles/kibana
  links:
    - elasticsearch:elasticsearch
proxy:
  extends:
    file: docker-compose-common.yml
    service: proxy
  build: dockerfiles/logstash-email-proxy
  links:
    - logs:logs
  restart: always
  command: sh run.sh 2020/tcp,logs:5000 2020/udp,logs:5000 2021/tcp,logs:5001 2021/udp,logs:5001
